LearningChannel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('index.urls')),
    path('authentication/', include('authentication.urls')),
    path('user/', include('user.urls')),
    path('learning/', include('learning.urls')),
    path('religion/', include('religion.urls')),
    path('admin/', admin.site.urls),
]

authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('change-password', views.change_password_view,
         name='change-password'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('<slug:username>/', views.user_view, name='user'),
    path('edit-homepage', views.edit_homepage_view, name='edit-homepage'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.validators import validate_slug, ValidationError


def login_view(request):
    nxt = request.GET.get('next', reverse('index:index'))
    if request.user.is_authenticated:
        return redirect(nxt)
    username = error = ''
    if request.method == 'POST':
        nxt = request.POST.get('next')
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(nxt)
        else:
            error = '用户名或密码错误！'
    context = {
        'username': username,
        'error': error,
        'next': nxt,
    }
    return render(request, 'authentication/login.html',
                  context=context)


def logout_view(request):
    nxt = request.GET.get('next')
    if not nxt:
        nxt = reverse('index:index')
    logout(request)
    return redirect(nxt)


def register_view(request):
    # return redirect(reverse('authentication:login'))
    nxt = request.GET.get('next', reverse('index:index'))
    if request.user.is_authenticated:
        return redirect(nxt)
    username = error = ''
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        password2 = request.POST.get('password2', '')
        if 4 <= len(username) <= 20:
            try:
                validate_slug(username)
            except ValidationError:
                error = '用户名不合规！'
            else:
                if password == password2:
                    if len(password) <= 100:
                        usernames = [
                            user.username for user in User.objects.all()
                        ]
                        if username not in usernames:
                            user = User.objects.create_user(
                                username=username, password=password
                            )
                            group_names = [
                                group.name for group in Group.objects.all()
                            ]
                            group_name = '普通用户'
                            if group_name in group_names:
                                group = Group.objects.get(name=group_name)
                            else:
                                group = Group.objects.create(name='普通用户')
                                group.save()
                            user.groups.add(group)
                            user.save()
                            login(request, user)
                            return redirect(nxt)
                        else:
                            error = '用户名已存在！'
                    else:
                        error = '密码过长！'
                else:
                    error = '密码不一致！'
        else:
            error = '用户名长度不正确！'
    context = {
        'username': username,
        'error': error,
        'next': nxt,
    }
    return render(request, 'authentication/register.html',
                  context=context)


@login_required
def change_password_view(request):
    user = request.user
    info = error = ''
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        if user.check_password(old_password):
            if password == password2:
                if len(password) <= 100:
                    user.set_password(password)
                    user.save()
                    info = '密码修改成功！'
                    login(request, user)
                else:
                    error = '新密码过长！'
            else:
                error = '新密码不一致！'
        else:
            error = '旧密码不正确！'
    context = {
        'username': user.username,
        'info': info,
        'error': error,
    }
    return render(request, 'authentication/change_password.html',
                  context)

authentication/templates/authentication/change_password.html
{% extends "index/base.html" %}

{% block title %}注册{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-gear" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
      <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
      <path fill-rule="evenodd" d="M11.886 9.46c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382l.045-.148ZM14 12.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"/>
    </svg>
    更改密码
  </h4>
  <div class="card-body">
    <form method="post" action="{% url 'authentication:change-password' %}">
      {% csrf_token %}
      <input type="hidden" value="{{ next }}" name="next">
      <fieldset disabled>
        <div class="mb-3">
          <label for="username" class="form-label">用户名</label>
          <input type="text" class="form-control" id="username"
                 value="{{ username }}">
        </div>
      </fieldset>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="old_password"
               name="old_password" placeholder="密码">
        <label for="old_password">旧密码</label>
        <div class="form-text">验证操作由用户本人完成。</div>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password"
               name="password" placeholder="密码">
        <label for="password">新密码</label>
        <div class="form-text">长度限制：0~100位。</div>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password2"
               name="password2" placeholder="验证密码">
        <label for="password2">验证新密码</label>
        <div class="form-text">应与密码相同，以保证输入无误。</div>
      </div>
      {% if info %}
      <div class="alert alert-info" role="alert">
        {{ info }}
      </div>
      {% endif %}
      {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
      {% endif %}
      <div class="d-grid">
        <button type="submit" class="btn btn-primary">更改密码</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends "index/base.html" %}

{% block title %}登录{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-check" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm1.679-4.493a.5.5 0 1 0-.858-.514l-1.17 1.95-.547-.547a.5.5 0 0 0-.708.708l.774.773a.75.75 0 0 0 1.174-.144l1.335-2.226ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
      <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
    </svg>
    登录
  </h4>
  <div class="card-body">
    <form method="post" action="{% url 'authentication:login' %}">
      {% csrf_token %}
      <input type="hidden" value="{{ next }}" name="next">
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="username"
               name="username" placeholder="用户名"
               value="{{ username }}">
        <label for="username">用户名</label>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password"
               name="password" placeholder="密码">
        <label for="password">密码</label>
      </div>
      {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
      {% endif %}
      <a href="{% url 'authentication:register' %}"
         class="link-primary text-decoration-none">
        没有账号？先去注册~
      </a>
      <div class="d-grid">
        <button type="submit" class="btn btn-primary">登录</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

authentication/templates/authentication/register.html
{% extends "index/base.html" %}

{% block title %}注册{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5a.5.5 0 0 0-1 0v1h-1a.5.5 0 0 0 0 1h1v1a.5.5 0 0 0 1 0v-1h1a.5.5 0 0 0 0-1h-1v-1Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
      <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
    </svg>
    注册
  </h4>
  <div class="card-body">
    <form method="post" action="{% url 'authentication:register' %}">
      {% csrf_token %}
      <input type="hidden" value="{{ next }}" name="next">
      <div class="form-floating mb-3">
        <input type="text" class="form-control" id="username"
               name="username" placeholder="用户名"
               value="{{ username }}">
        <label for="username">用户名</label>
        <div class="form-text">
          长度限制：4~20位，只包含字母、数字、下划线或连字符。
        </div>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password"
               name="password" placeholder="密码">
        <label for="password">密码</label>
        <div class="form-text">长度限制：0~100位。</div>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control" id="password2"
               name="password2" placeholder="验证密码">
        <label for="password2">验证密码</label>
        <div class="form-text">应与密码相同，以保证输入无误。</div>
      </div>
      {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
      {% endif %}
      <a href="{% url 'authentication:login' %}"
         class="link-primary text-decoration-none">
        已有账号？立即登录~
      </a>
      <div class="d-grid">
        <button type="submit" class="btn btn-primary">注册</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}