LearningChannel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('index.urls')),
    path('authentication/', include('authentication.urls')),
    path('user/', include('user.urls')),
    path('learning/', include('learning.urls')),
    path('religion/', include('religion.urls')),
    path('admin/', admin.site.urls),
]

learning/urls.py
from django.urls import path

from . import views

app_name = 'learning'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('search', views.search_view, name='search'),
    path('<slug:channel_title>/', views.channel_view, name='channel'),
    path('<slug:channel_title>/new', views.new_topic_view, name='new-topic'),
    path('<slug:channel_title>/delete/<int:topic_id>', views.delete_topic_view, name='delete-topic'),
    path('<slug:channel_title>/<int:topic_id>/', views.topic_view, name='topic'),
    path('<slug:channel_title>/<int:topic_id>/new', views.new_entry_view, name='new-entry'),
    path('<slug:channel_title>/<int:topic_id>/delete/<int:entry_id>', views.delete_entry_view, name='delete-entry'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('<slug:username>/', views.user_view, name='user'),
    path('edit-homepage', views.edit_homepage_view, name='edit-homepage'),
]

learning/models.py
from django.db import models
from django.contrib.auth.models import User


class Channel(models.Model):
    title = models.SlugField(max_length=20, primary_key=True)
    introduction = models.TextField()

    def __str__(self):
        return f'{self.title}频道：' \
               f'{self.introduction[:50]+"……" if len(self.introduction) > 50 else self.introduction}'

    class Meta:
        verbose_name = '频道'
        verbose_name_plural = '频道'


class Topic(models.Model):
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.channel.title}频道的主题：{self.name}'

    class Meta:
        verbose_name = '主题'
        verbose_name_plural = '主题'


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f'用户{self.owner.username}在主题“{self.topic.name}”的条目：' \
               f'{self.content[:50]+"……" if len(self.content) > 50 else self.content}'

    class Meta:
        verbose_name = '条目'
        verbose_name_plural = '条目'

learning/views.py
import html

from django.shortcuts import render, get_object_or_404, reverse, redirect, Http404
from django.contrib.auth.decorators import login_required
import markdown

from .models import Channel, Topic, Entry
from religion.models import Token


def to_markdown(text):
    return markdown.markdown(html.escape(text.strip()))


@login_required
def index_view(request):
    channels = []
    for channel in Channel.objects.all():
        channels.append({
            'title': channel.title,
            'title_show': channel.title.replace('-', ' '),
            'introduction': to_markdown(channel.introduction),
        })
    context = {
        'channels': channels,
    }
    return render(request, 'learning/index.html', context=context)


@login_required
def channel_view(request, channel_title):
    channel = get_object_or_404(Channel, title=channel_title)
    context = {
        'channel': {
            'title': channel_title,
            'title_show': channel_title.replace('-', ' '),
            'introduction': to_markdown(channel.introduction),
        },
        'topics': Topic.objects.filter(channel=channel),
    }
    return render(request, 'learning/channel.html', context=context)


@login_required
def new_topic_view(request, channel_title):
    channel = get_object_or_404(Channel, title=channel_title)
    if request.method == 'POST':
        topic_name = request.POST.get('topic-name', '').strip()
        if topic_name:
            topic = Topic(channel=channel, creator=request.user, name=topic_name)
            topic.save()
            kwargs = {
                'channel_title': channel_title,
                'topic_id': topic.id,
            }
            return redirect(reverse('learning:topic', kwargs=kwargs))
    kwargs = {
        'channel_title': channel_title,
    }
    return redirect(reverse('learning:channel', kwargs=kwargs))


@login_required
def delete_topic_view(request, channel_title, topic_id):
    channel = get_object_or_404(Channel, title=channel_title)
    topic = get_object_or_404(Topic, channel=channel, id=topic_id)
    if request.user != topic.creator and not request.user.is_superuser:
        raise Http404
    topic.delete()
    kwargs = {
        'channel_title': channel_title,
    }
    return redirect(reverse('learning:channel', kwargs=kwargs))


@login_required
def topic_view(request, channel_title, topic_id):
    channel = get_object_or_404(Channel, title=channel_title)
    topic = get_object_or_404(Topic, channel=channel, id=topic_id)
    entries = []
    for entry in Entry.objects.filter(topic=topic):
        entries.append({
            'owner': entry.owner,
            'id': entry.id,
            'content': to_markdown(entry.content),
        })
    context = {
        'channel': {
            'title': channel_title,
            'title_show': channel_title.replace('-', ' '),
        },
        'topic': topic,
        'entries': entries,
    }
    return render(request, 'learning/topic.html', context=context)


@login_required
def new_entry_view(request, channel_title, topic_id):
    channel = get_object_or_404(Channel, title=channel_title)
    topic = get_object_or_404(Topic, channel=channel, id=topic_id)
    if request.method == 'POST':
        entry_content = request.POST.get('entry-content', '').strip()
        if entry_content:
            entry = Entry(topic=topic, owner=request.user, content=entry_content)
            entry.save()
    kwargs = {
        'channel_title': channel_title,
        'topic_id': topic_id,
    }
    return redirect(reverse('learning:topic', kwargs=kwargs))


@login_required
def delete_entry_view(request, channel_title, topic_id, entry_id):
    channel = get_object_or_404(Channel, title=channel_title)
    topic = get_object_or_404(Topic, channel=channel, id=topic_id)
    entry = get_object_or_404(Entry, topic=topic, id=entry_id, owner=request.user)
    if request.user != entry.owner and not request.user.is_superuser:
        raise Http404
    entry.delete()
    kwargs = {
        'channel_title': channel_title,
        'topic_id': topic_id,
    }
    return redirect(reverse('learning:topic', kwargs=kwargs))


@login_required
def search_view(request):
    search = request.GET.get('search', '').strip().lower()
    if search:
        channels = []
        if search == 'older never die':
            token, created = Token.objects.get_or_create(owner=request.user)
            if created:
                print('New token created by user:', token.owner)
        for channel in Channel.objects.all():
            if search in channel.title.lower() or search in channel.introduction.lower():
                channels.append({
                    'title': channel.title,
                    'title_show': channel.title.replace('-', ' '),
                    'introduction': to_markdown(channel.introduction),
                })
        context = {
            'channels': channels,
            'search': search,
        }
        return render(request, 'learning/search.html', context=context)
    return redirect(reverse('learning:index'))

learning/templates/learning/channel.html
{% extends "index/base.html" %}

{% block title %}{{ channel.title_show }}频道{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
      <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
    </svg>
    {{ channel.title_show }}频道
  </h4>
  <div class="card-body">
    <div class="card card-body mb-3">
      {{ channel.introduction|safe }}
    </div>
    {% if topics %}
    <hr>
    {% for topic in topics %}
    <div class="card">
      <h6 class="card-header">
        <a href="{% url 'user:user' topic.creator.username %}" target="_blank"
           class="link-success text-decoration-none">
          {{ topic.creator.username }}
        </a>
      </h6>
      <a href="{% url 'learning:topic' channel.title topic.id %}"
         class="link-primary text-decoration-none card-body">
        {{ topic.name }}
      </a>
    </div>
    {% endfor %}
    {% else %}
    <hr>
    <div class="card card-body">
      还没有主题哦~
    </div>
    {% endif %}
    <hr>
    <form action="{% url 'learning:new-topic' channel.title %}" method="post">
      {% csrf_token %}
      <div class="card card-body mb-3">
        <div class="row">
          <div class="col-8">
            <input type="text" class="form-control" id="topic-name" name="topic-name" maxlength="100"
                   placeholder="新主题">
          </div>
          <div class="col-4">
            <div class="d-grid">
              <button class="btn btn-primary" type="submit">增加</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

learning/templates/learning/index.html
{% extends "index/base.html" %}

{% block title %}学习{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
      <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
    </svg>
    学习
  </h4>
  <div class="card-body">
    {% if channels %}
    <form action="{% url 'learning:search' %}" method="get">
      <div class="card card-body mb-3">
        <div class="row">
          <div class="col-8">
              <input type="search" class="form-control" id="search" name="search" placeholder="搜索">
          </div>
          <div class="col-4">
            <div class="d-grid">
              <button class="btn btn-primary" type="submit">搜索</button>
            </div>
          </div>
        </div>
      </div>
    </form>
    <div class="row">
      {% for channel in channels %}
      <div class="col-3 mb-3">
        <a href="{% url 'learning:channel' channel.title %}"
           class="card text-decoration-none text-black h-100">
          <h5 class="card-header">
            {{ channel.title_show }}
          </h5>
          <div class="card-body">
            {{ channel.introduction|safe }}
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <p class="card-text">
      还没有频道哦~
    </p>
    <p class="card-text">
      如果你想创建频道的话，请通知管理员~
    </p>
    {% endif %}
  </div>
</div>
{% endblock %}

learning/templates/learning/search.html
{% extends "index/base.html" %}

{% block title %}搜索{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    搜索
  </h4>
  <div class="card-body">
    <form action="{% url 'learning:search' %}" method="get">
      <div class="card card-body mb-3">
        <div class="row">
          <div class="col-8">
              <input type="search" class="form-control" id="search" name="search" value="{{ search }}" placeholder="搜索">
          </div>
          <div class="col-4">
            <div class="d-grid">
              <button class="btn btn-primary" type="submit">搜索</button>
            </div>
          </div>
        </div>
      </div>
    </form>
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% else %}
    {% if channels %}
    <div class="row">
      {% for channel in channels %}
      <div class="col-3 mb-3">
        <a href="{% url 'learning:channel' channel.title %}"
           class="card text-decoration-none text-black h-100">
          <h5 class="card-header">
            {{ channel.title_show }}
          </h5>
          <div class="card-body">
            {{ channel.introduction|safe }}
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
      没有搜到这样的频道哦~
    </div>
    {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

learning/templates/learning/topic.html
{% extends "index/base.html" %}

{% block title %}{{ channel.title_show }}频道 - {{ topic.name }}{% endblock %}

{% block content %}
<div class="card" style="margin-top: 20px;">
  <h4 class="card-header">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
      <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
    </svg>
    <a href="{% url 'learning:channel' channel.title %}" class="link-primary text-decoration-none">
      {{ channel.title_show }}频道
    </a>
    <a href="{% url 'user:user' topic.creator.username %}" target="_blank"
       class="link-success text-decoration-none">
      {{ topic.creator.username }}
    </a>
    {{ topic.name }}
    {% if topic.creator == request.user or request.user.is_superuser %}
    <a href="{% url 'learning:delete-topic' channel.title topic.id %}" class="link-danger text-decoration-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
      </svg>
    </a>
    {% endif %}
  </h4>
  <div class="card-body">
    {% if entries %}
    {% for entry in entries %}
    <div class="card mb-3">
      <div class="card-header">
        <a href="{% url 'user:user' entry.owner.username %}" target="_blank"
           class="link-success text-decoration-none">
          {{ entry.owner.username }}
        </a>
        {% if entry.owner == request.user or request.user.is_superuser %}
        <a href="{% url 'learning:delete-entry' channel.title topic.id entry.id %}" class="link-danger text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </a>
        {% endif %}
      </div>
      <div class="card-body">
        {{ entry.content|safe }}
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="card card-body mb-3">
      还没有条目哦~
    </div>
    {% endif %}
    <hr>
    <form action="{% url 'learning:new-entry' channel.title topic.id %}" method="post">
      {% csrf_token %}
      <div class="card card-body mb-3">
        <textarea class="form-control mb-3" id="entry-content" name="entry-content"
                  placeholder="新条目"></textarea>
        <div class="d-grid">
          <button class="btn btn-primary" type="submit">增加</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}