LearningChannel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('index.urls')),
    path('authentication/', include('authentication.urls')),
    path('user/', include('user.urls')),
    path('learning/', include('learning.urls')),
    path('religion/', include('religion.urls')),
    path('admin/', admin.site.urls),
]

authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('change-password', views.change_password_view,
         name='change-password'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('<slug:username>/', views.user_view, name='user'),
    path('edit-homepage', views.edit_homepage_view, name='edit-homepage'),
]

index/templates/index/index.html
{% extends "index/base.html" %}

{% block title %}主页{% endblock %}

{% block content %}
<div class="card card-body" style="margin-top: 20px;">
  <h4 class="card-title">
    {% if user.is_authenticated %}
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-emoji-laughing" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M12.331 9.5a1 1 0 0 1 0 1A4.998 4.998 0 0 1 8 13a4.998 4.998 0 0 1-4.33-2.5A1 1 0 0 1 4.535 9h6.93a1 1 0 0 1 .866.5zM7 6.5c0 .828-.448 0-1 0s-1 .828-1 0S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 0-1 0s-1 .828-1 0S9.448 5 10 5s1 .672 1 1.5z"/>
    </svg>
    {% else %}
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-emoji-smile" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
    </svg>
    {% endif %}
    欢迎使用学习频道！
  </h4>
  <hr>
  {% if user.is_authenticated %}
  <p class="card-text">现在您可以去使用本网站的各种功能了！</p>
  {% else %}
  <p class="card-text">
    您可以在
    <a href="{% url 'authentication:login' %}" class="link-primary text-decoration-none">
      登录
    </a>
    |
    <a href="{% url 'authentication:register' %}" class="link-primary text-decoration-none">
      注册
    </a>
    后使用本网站的各种功能。
  </p>
  {% endif %}
</div>
{% endblock %}

{% block extension %}
<hr>
<p class="text-center">
  Copyright &copy; 2023 xiaoYG. All rights reversed.
</p>
{% endblock %}